// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type LatLng struct {
	Latitude  float64 `json:"latitude"`
	Longitude float64 `json:"longitude"`
}

type Place struct {
	ID     string  `json:"id"`
	Name   string  `json:"name"`
	LatLng *LatLng `json:"latLng"`
}
